#!/bin/bash
if [ -z ${PACK_ISCSI_MODULE_PATH+x} ] ; then
  export PACK_ISCSI_MODULE_PATH="${PARCELS_ROOT}/${PARCEL_DIRNAME}"
else
  export PACK_ISCSI_MODULE_PATH="${PACK_ISCSI_MODULE_PATH}:{PARCELS_ROOT}/${PARCEL_DIRNAME}"
fi
